language: c

env:
  - LUA='Lua 5.1' USE_LUA='USE_LUA=ON'
  - LUA='Lua 5.2' USE_LUA='USE_LUA52=ON'
  - LUA='LuaJIT 2.0' USE_LUA='USE_LUAJIT=ON'

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install libmagickcore-dev libmagickwand-dev libgraphicsmagick1-dev

script:
  - cmake -D${USE_LUA} -DUSE_IMAGEMAGICK=ON .
  - make
  - make unittest